#!/usr/bin/env php
<?php

require(__DIR__ . '/vendor/autoload.php');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));


$modeFile = __DIR__ . '/config/mode.php';
$mode = 'prod';
if (file_exists($modeFile)) {
    $mode = trim(file_get_contents($modeFile));
}

$env = new \janisto\environment\Environment(__DIR__ . '/config', $mode);
$env->setup();
$exitCode = (new yii\console\Application($env->console))->run();
exit($exitCode);